[project]
name = "auto-trader"
version = "0.1.0"
dependencies = [
    "google-cloud-secret-manager",
    "google-cloud-storage",
    "lightgbm >= 3.3.2",
    "neptune-client",
    "numpy",
    "hydra-core",
    "pandas >= 1.3.5",
    "torch",
    "scikit-learn",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
    "pyproject-flake8",
    "mypy",
    "pytest",
    "pytest-mock",
]

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
