[project]
name = "auto-trader"
version = "0.1.0"
dependencies = [
    "google-cloud-secret-manager",
    "google-cloud-storage",
    "lightgbm >= 3.3.2",
    "neptune-client",
    "numpy",
    "hydra-core",
    "pandas >= 1.3.5",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
    "mypy",
]
