name: Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Change directory
        run: |
          cd src/auto_trader
      - name: Lint
        run: |
          black --check .
          isort --check .
          pflake8 .
      - name: Test
        run: |
          pytest
